export enum EventRoutes {
	REGISTER = "register",
	UNREGISTER = "unregister",
	CLUB = "club",
	EVENT_CODE = ":code",
	EVENT = "event",
	GET_EVENT_BY_CLUB = "getEventByClub",
	GET_EVENT_USERS_BY_CODE = "getEventUsersByCode",
	GET_COUNT_BY_CODE = "getCountByCode",
	UPDATE_MAX_CAP = "updateMaxCap",
	ACTIVATE_EVENT = "activateEvent",
	GET_EVENT_BY_USER = "getEvent",
	GET_USER_DETAIL_BY_EVENT_CODE = "getUserDetailByEventCode",
	GET_USERS_DETAILS_FOR_EVENT = "getUsersDetailsForEvent",
}
