export enum StaffRoutes {
	REGISTER = "register",
	LOGIN = "login",
	VERIFY = "verify",
	DENY = "deny",
	DELETE = "deleteStaff",
	FORGOT_PASSWORD = "forgotpassword",
	LOGOUT = "logout",
	GET_STAFFS = "",
	GET_CURRENT_STAFF = "current",
	GET_USER_ID_BY_EMAIL = "getUserIdByEmail",
	GET_BOOKING_BY_EMAIL = "getBookingByEmail",
	GET_OFFLINE_TICKETS_ISSUED = "getOfflineTicketsIssued",
	GET_TOTAL_REGISTRATIONS = "getTotalRegistrations",
	GET_TOTAL_TICKETS_SOLD = "getTotalTicketsSold",
	DELETE_USER = "deleteUser",
	GET_USER_BY_USER_ID = "getUserByUserID",
}
